apiVersion: v1
kind: Namespace
metadata:
  name: test-eks-lambda
---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::$ACCOUND_ID:role/eksctl-aws-dna-nodegroup-node-gro-NodeInstanceRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::$ACCOUND_ID:role/chatbot-lambda-eks
      username: eks-lambda-user
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-lamba-sa
  namespace: test-eks-lambda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-eks-lambda
  name: eks-lambda-role
rules:
- apiGroups: [""]
  resources: ["pods","services","namespaces","nodes","deployments","ingresses","horizontalpodautoscalers"]
  verbs: ["get", "watch", "list","patch","create","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eks-lambda-role-binding
  namespace: test-eks-lambda
subjects:
- kind: ServiceAccount
  name: eks-lambda-sa
  namespace: test-eks-lambda
roleRef:
  kind: Role
  name: eks-lambda-role
  apiGroup: rbac.authorization.k8s.io