apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: carts-svc-virtual-node
  namespace: sock-shop
spec:
  podSelector:
    matchLabels:
      name: carts
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: carts-svc-virtual-node.sock-shop.svc.cluster.local