
name: Restart
on:
  repository_dispatch:
    types: [restart]
jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.20.0'
      - name: install helm
        uses: azure/setup-helm@v3
        with:
          version: latest
      - name: update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER }}
          echo ${{ github.event.client_payload.namespace }}
          echo ${{ github.event.client_payload.deployment-name }}
      - name: Restart deployment
        run: |
          kubectl -n ${{ github.event.client_payload.namespace }} rollout restart deployment ${{ github.event.client_payload.deployment-name }}
      - name: Send to Slack (Success)
        if: success()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "attachments": [
                  {
                      "fallback": "✅ Success Restart Deployment",
                      "color": "#36AE7C",
                      "text": "✅ Success Restart Deployment",
                      "fields": [
                          {
                              "title": "Deployment",
                              "value": "${{ github.event.client_payload.deployment-name }}",
                              "short": true
                          },
                          {
                              "title": "Namespace",
                              "value": "${{ github.event.client_payload.namespace }}",
                              "short": true
                          }
                      ]
                  }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Send to Slack(Failure)
        if: failure()
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "attachments": [
                  {
                      "fallback": "❌ Failure Restart Deployment",
                      "color": "#EB5353",
                      "text": "❌ Failure Restart Deployment",
                      "fields": [
                          {
                              "title": "Deployment",
                              "value": "${{ github.event.client_payload.deployment-name }}",
                              "short": true
                          },
                          {
                              "title": "Namespace",
                              "value": "${{ github.event.client_payload.namespace }}",
                              "short": true
                          }
                      ]
                  }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK